# Provision a single instance
run-instance : provision-instance.ikt

# Manage a group of nodes
scale-group : scale-group.ikt

# List instances
list-instances : list-instances.sh

# Destroy all
destroy-all : destroy-instances.sh
